#!/bin/bash
# Add Compasss repositories for OpenDV programs

echo 'deb [arch=armhf,amd64] http://archive.compasslinux.org/ wilderness main' >/etc/apt/sources.list.d/compass.list
wget http://archive.compasslinux.org/compass.gpg.key -O - | sudo apt-key add -
apt-get update

# apt-get install ambeserver
# apt-get install ircddbgateway ircddbgatewayd
# apt-get install remotecontrol remotecontrold


