#!/usr/bin/env bash

# Initialize number of attempts
reachable=2
while [ $reachable -ne 0 ]; do
  # Check host
  # ping -q -c 1 -W 1 "www.google.com" > /dev/null 2>&1
  wget http://google.com/robots.txt -O /tmp/robots.txt -T 10 &> /dev/null
  # Check return code
  if [ $? -eq 0 ]; then
    # Success, we can exit with the right return code
    exit 0
    return
  fi
  # Network down, decrement counter and try again
  let reachable-=1
  # Sleep for one second
  sleep 1
done
# Network down, number of attempts exhausted, quiting
exit 1

# echo $?
